### ISSUE TITLE
Notification are not being shown when application is fully closed

### ISSUE THREAD

**Issue by studentutu** [Unity-Technologies/NotificationsSamples#1]
Good afternoon everyone,
we have built and run the demo on our Android device(Android 6.0). Everything works like a charm, but when the application is fully closed by the user, there are no notifications afterward...
Could you explain if the current version of Unity Mobile Notifications Package support push notification even when the app is not running?

**Comment by krisuman** [comment]
Hi @studentutu, I have exactly same issue. Did you found some solution for that?

**Comment by qwyt** [comment]
What device are you testing on? Seems that Huawei (including Honor) and Xiaomi utilize aggresive batter saver techniques which restrict app background activities unless the app has been whitelisted by the user in device settings. This means that any scheduled notifications will not be delivered if the app is closed or not running in the bacgkround on their devices.

**Comment by krisuman** [comment]
It was Huawei Honor 9 Lite ;)

**Comment by qq1545372477** [comment]
Samsung Galaxy S8 has the same issue

**Comment by MechaCondor** [comment]
Hi, Oppo R11 is also facing the same issue.

**Comment by Gifgroen** [comment]
When an app is closed the notification service receiving messages might not always run. But if this happens a user chose to actively kill it, aka he/she might not want notifications at that time. I understand the desire to activate users again when this happens. I am not sure if Android will allow/support this behavior. 

Long story short: this sounds like a restriction from Android, not Unity or this package.

**Comment by studentutu** [comment]
> 
> 
> What device are you testing on? Seems that Huawei (including Honor) and Xiaomi utilize aggresive batter saver techniques which restrict app background activities unless the app has been whitelisted by the user in device settings. This means that any scheduled notifications will not be delivered if the app is closed or not running in the bacgkround on their devices.

Yep, it was Xiaomi !
