### ISSUE TITLE
Notification remains on notifications list after clicked (Android)

### ISSUE THREAD

**Issue by tutibueno** [Unity-Technologies/NotificationsSamples#12]
Notifications are working nicely for my needs however when clicking on a notification (app is closed), the app opens but notification is not closed, it remains on notifications list. Am I doing something wrong?

**Comment by lukaslabaj** [comment]
Same issue here, did you found some solution please?

**Comment by tutibueno** [comment]
> Same issue here, did you found some solution please?

No solution yet

**Comment by ajon542** [comment]
Do either of these methods from the GameNotificationsManager work for you?
void DismissNotification(int notificationId)
void DismissAllNotifications()

**Comment by lukaslabaj** [comment]
Thanks @ajon542. I added DismissAllDisplayedNotifications() in AndroidNotificationsPlatform when application gets to foreground and it works perfectly.

**Comment by aurimasc** [comment]
I believe you need to set ShouldAutoCancel to true on your notifications.
