### ISSUE TITLE
Notifications do not appear on iOS 10.3.3

### ISSUE THREAD

**Issue by JabluszkoPL** [Unity-Technologies/NotificationsSamples#14]
Unity version: 2018.3.7f1
Mobile Notification version: 1.0.0 - preview v21 and v17
iOS version: 10.3.3
Devices: iPhone SE, iPad 9.6 (6th gen)
Feature: Local Notifications

Description:
The phone produces a reaction (vibration and sound) as if there was a new notification but the notifications centre is empty. Logs show that a notification has been sent.

How to reproduce:
1) Grab an iPhone with iOS 10.3.3
2) Launch the app
3) Trigger a local notification

**Comment by stalhandske** [comment]
I've noticed this same thing happening for me. Did you find any workaround?

**Comment by JabluszkoPL** [comment]
Unfortunately no

**Comment by vaidas-unity** [comment]
Hi, could you please check if this happens with Notifications package version 1.3.0?
