### ISSUE TITLE
1.0.2 package manager error

### ISSUE THREAD

**Issue by deveraturda2015** [Unity-Technologies/NotificationsSamples#15]
I received this error after installing the mobile notification from the package manager

Assembly has reference to non-existent assembly 'UnityEngine.TestRunner' (Packages/com.unity.mobile.notifications/Tests/Editor/Unity.Notifications.Tests.asmdef)

Version: Unity 2018.3.5f1

Reproduce steps
1. Create a new project
2. Import the mobile notification 1.0.2 from the Package Manager

**Comment by ChaosVan** [comment]
I received a same error

Assembly has reference to non-existent assembly 'UnityEngine.TestRunner' (Packages/com.unity.mobile.notifications/Tests/Editor/Unity.Notifications.Tests.asmdef)

Unity 2018.4.1f1

update from 1.0.0 p23

**Comment by deveraturda2015** [comment]
I rolled back to 1.0.0 p23 to make it work for a while. Please fix the 1.0.2 latest version

**Comment by hrabkin** [comment]
Same error

**Comment by luvjungle** [comment]
Same

**Comment by Goropocha** [comment]
same error.
Unity 2018.4.1f1

**Comment by LexaMV** [comment]
same error.
Unity 2018.4.2f1

**Comment by vietdungdev** [comment]
just delete test folder

**Comment by StefanoCecere** [comment]
i solved this error installing the package **com.unity.test-framework": "0.0.4-preview"**

**Comment by viliom1** [comment]
> just delete test folder

Fixed it for me on 2018.4.0f1

**Comment by qwyt** [comment]
This should be fixed on 1.0.3-preview.6

**Comment by cmcpasserby** [comment]
is 1.0.3 close to coming out, i would prefer not to use preview packages int my project. but that would not be too big a issue if its only a few weeks and i can update it later.
