### ISSUE TITLE
IL2CPP error: SafeArray element type Int64 is not supported

### ISSUE THREAD

**Issue by SamMcAlpine** [Unity-Technologies/NotificationsSamples#16]
I'm getting this error when trying to build using IL2CPP in 2019.2.0f1

IL2CPP error for method 'System.Void Unity.Notifications.Android.AndroidNotificationCenter::RegisterNotificationChannel(Unity.Notifications.Android.AndroidNotificationChannel)' in assembly '...\Temp\StagingArea\assets\bin\Data\Managed\Unity.Notifications.Android.dll'
Additional information: SafeArray element type Int64 is not supported.

Thanks

**Comment by GorillaOne** [comment]
Getting the same error.

**Comment by qwyt** [comment]
This is a regression in IL2CPP on 2019.2 and above.

Fixed in 1.0.3-preview.6

**Comment by praleks** [comment]
1.0.3-preview.6
Not Fixed!

**Comment by milamila33** [comment]
i am getting this error on unity 2019.2.4f1. Should i change the unity version?
