### ISSUE TITLE
Android - Doesn't show my app when clicking on a notification

### ISSUE THREAD

**Issue by momone50** [Unity-Technologies/NotificationsSamples#17]
Hi,
Notifications are fired and i can see them, but when i click on it, it should open my app. But it doesn't.

Android 5.0, Acer Iconia

Thanks

**Comment by lucas-9510** [comment]
I have same issue, did you found some solution please?

**Comment by momone50** [comment]
Hi, in my case, was due to Firebase Cloud Messaging, messing with android manifest (because of Custom Activity). The last version of the Unity Notification package gives you an option to overcome the problem. 
You can now choose a Custom Android ctivity Name. If you have the same problem, you can put this in the field :
com.google.firebase.MessagingUnityPlayerActivity

**Comment by momone50** [comment]
![2019-08-21 15_34_12-Window](https://user-images.githubusercontent.com/54250546/63436692-6644d100-c429-11e9-86e5-09cffbf2d0da.png)

**Comment by momone50** [comment]
I'm using the Unity Notification Package not the Wrapper you can find on Github. Don't know if it change something.
Plugin version : 1.0.3

**Comment by lucas-9510** [comment]
Thank you very much. I solved.
