### ISSUE TITLE
Push at 12 o'clock every day, how to do it? I did not find related examples.

### ISSUE THREAD

**Issue by HugoFang** [Unity-Technologies/NotificationsSamples#19]
(；′⌒`)
No "repeat" or "interval" related content found in "IGameNotification"

**Comment by jacobfrank250** [comment]
I would like to implement the same feature in my app. Has anyone found a solution?

**Comment by HugoFang** [comment]
I replaced this with https://github.com/Agasper/unity-android-notifications
