### ISSUE TITLE
Support Sound And Vibrate?

### ISSUE THREAD

**Issue by aprius** [Unity-Technologies/NotificationsSamples#2]
I can't find properties sound and flag bool for vibrate in struct AndroidNotification in namespace Unity.Notifications.Android. Is it not supported?

**Comment by aprius** [comment]
ya i found vibrate in the AndroidNotificationChannel , default it is true but when i run in device it not make vibrate

**Comment by vaidasma** [comment]
We're not able to reproduce the vibration issue on Notification package 1.4.1 . If you're still experiencing this issue on the mentioned release, please submit another issue with included info about your device, it's OS, used Unity release, and any other information that you might have that's potentially relevant.

As for the sound part, I'll be submitting a feature request.
