### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by mcrvaz** [Unity-Technologies/NotificationsSamples#22]
ANDROID

Are emojis currently supported by this package?
I've tried scheduling notifications with emoji symbols and with their unicode characters, even with surrogate pairs, but it some of them don't work as expected.

Examples: 
⭐ (U+2B50) Works fine
😍(U+1F60D) Doesn't work

This happened on Android 4.4.4.
Also tested on Android 7.0 and 6.0.1 and it worked correctly.

**Comment by mcrvaz** [comment]
This actually seems to crash on one of our Android 5.1.1 devices (SM-J105B)

`10-01 06:30:09.288 F/art     (17958): sart/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xf0
10-01 06:30:09.288 F/art     (17958): sart/runtime/check_jni.cc:65]     string: 'A carga! 📦'
10-01 06:30:09.288 F/art     (17958): sart/runtime/check_jni.cc:65]     in call to NewStringUTF
10-01 06:30:09.288 F/art     (17958): sart/runtime/check_jni.cc:65]     from boolean com.unity3d.player.UnityPlayer.nativeRender()`

**Comment by CodeMasterYi** [comment]
It is not what this plugin can do for us, I think.=。=

**Comment by aurimasc** [comment]
Unity did have issues with Unicode in the past, but those should be fixed now.
