### ISSUE TITLE
First fire time parameter for iOSNotificationTimeIntervalTrigger

### ISSUE THREAD

**Issue by LSDemian** [Unity-Technologies/NotificationsSamples#24]
Hi
We really would like to be able to set a first fire time for repeating notifications on ios just like on the android. For example, display first notification in 1 minute and after this repeat it every hour. Is it possible to add this feature?

**Comment by aurimasc** [comment]
Our API is a wrapper on top of OS API. iOS has two types of time-based triggers: time interval and calendar, neither of which has direct support for what you ask.
So the solution is to either create many calendar triggered notifications or a single calendar based notification, uppon receiving which you would schedule a repeating time interval based notification.
For we now we don't intend to implement such state machine to support this feature.
