### ISSUE TITLE
Grey texture on Android automated builds

### ISSUE THREAD

**Issue by AnthonyDemanueleFSG** [Unity-Technologies/NotificationsSamples#25]
We are having an issue with notifications showing a grey 'large icon' texture when built through a build server. (Others are having the same issue as reported here: https://forum.unity.com/threads/mobile-notification-preview-package.620227/)

Unity2019.1.10f1

![NotificationsBug](https://user-images.githubusercontent.com/49918064/67847629-73ee9500-fb03-11e9-97e9-38d4ad22506a.png)

Log when the **'Wrong Grey'** notification is shown:
D/PhoneStatusBar(3466): addNotification key=0|com.**.**|#########|null|**10718**

Log when the **'Good icon'** notification is shown:
D/PhoneStatusBar(3466): addNotification key=0|com.**.**|#########|null|**10719**

Is there something we can do to fix this, please?
Thank you.

**Comment by aurimasc** [comment]
I believe this problem has been fixed in Unity.
