### ISSUE TITLE
Notification not working on Android 7.0 or below

### ISSUE THREAD

**Issue by BurningBlueFox** [Unity-Technologies/NotificationsSamples#26]
After implementing the api as the documentation there seems to be a problem with Android on 7.0 or versions below, the notification never arrives, this isn't a problem on android 8.0 and 9.0

**Comment by vaidasma** [comment]
Hello, does the issue still reoccur on the latest notification package (1.4.1) ?

Both sending and cancelling notification works on the following devices tested:
• Xiaomi Mi 5s (MI 5s), OS: 6.0.1
• Samsung Galaxy S8 USA (SM-G950U), OS: 7.0.0

I'm closing the issue for now, however, if it still does not work for you, please contact us again and provide the names of the devices that are able to reproduce this issue!
