### ISSUE TITLE
can I get callBack when Notification was clicked?

### ISSUE THREAD

**Issue by TWBestATM** [Unity-Technologies/NotificationsSamples#3]
when I click notification open game
can I get whose ID  I click?

**Comment by marcelino-borges** [comment]
Did you get it? I have tried this too, using the OnNotificationReceived method. but no success...

**Comment by TWBestATM** [comment]
@marcelino-borges  They fix this bug in new version ,unfortunately is min support is 2018.3,my version 2018.2 and can't   update immediately,some package problem

**Comment by qwyt** [comment]
You can retrieve the notification used to open the app (or bring it back from background) by calling `AndroidNotificationCenter.GetLastNotificationIntent()`. OnNotificationReceived only works when the app is running.
