### ISSUE TITLE
Can we set "UNITY_USES_REMOTE_NOTIFICATIONS 0"

### ISSUE THREAD

**Issue by leethirty** [Unity-Technologies/NotificationsSamples#31]
We found that the "UNITY_USES_REMOTE_NOTIFICATIONS 1" worked all the time in iOSNotificationPostProcess.cs.  Can we set "UNITY_USES_REMOTE_NOTIFICATIONS 0", when we don't need remote notification ?

**Comment by vaidas-unity** [comment]
Fixed in upcoming 1.3.1 release.
