### ISSUE TITLE
Consider adding repeatable notification support? (Android)

### ISSUE THREAD

**Issue by echoMikeO** [Unity-Technologies/NotificationsSamples#33]
I've used this wrapper for my mobile game on Android, but I found it lack of this feature. 
Since the API documentation has a RepeatInterval property in AndroidNotification class, I recommend adding this feature.
For now I just implemented RepeatInterval in AndroidGameNotification and put a repeat boolean check in GameNotificationManager so that it will refresh DeliveryTime instead of removing repeatable notifications . But without digging enough into the Manager logic, repeatble notification would still not functions perfectly such as somethimes being removed after clicking it to get back into the game.

Updating this feature would be nice. Or can I have some suggestions on implementing it?

**Comment by CodeMasterYi** [comment]
Same here!

**Comment by vaidasma** [comment]
Hello, the repeatable notifications as well as notification rescheduling is up and running in our current releases of Mobile Notifications. If that's not exactly what you were looking for, please do contact us any time and share your observations!
