### ISSUE TITLE
iOSNotificationCenter.GetLastRespondedNotification() does not work with Firebase plugin on ios

### ISSUE THREAD

**Issue by guntarspolis** [Unity-Technologies/NotificationsSamples#35]
iOSNotificationCenter.GetLastRespondedNotification() does not work with Firebase plugin on iOS.Always returns null. 

Firebase 6.7.0 for Unity, including :
FirebaseAnalytics
FirebaseMessaging
FirebaseAnalytics

any suggestions?

**Comment by vishakh-av** [comment]
I'm also facing the same issue with Firebase and Mobile Notifications. For me iOSNotificationCenter.GetLastRespondedNotification() returns null only when app that was killed is launched clicking unity's local notification. It does not work even when firebase is not initialised after lauched..  It works if app is launched by clicking notification when it was minimised.

**Comment by guntarspolis** [comment]
@vishakh-av 

I've opened an issue here as-well. If you have extra info please add it there.

https://github.com/firebase/firebase-unity-sdk/issues/377

**Comment by vzlomvl** [comment]
We have same issue.

**Comment by alishahriyari** [comment]
Same

**Comment by aurimasc** [comment]
Based on this comment:
https://github.com/firebase/firebase-unity-sdk/issues/377

Firebase removed the delegate Unity has registered, so Unity notifications package doesn't receive notification.

**Comment by mstf66x** [comment]
still doesn't work
