### ISSUE TITLE
Small and large icons replaced by Unity Icon when using BigTextStyle

### ISSUE THREAD

**Issue by SamTyurenkov** [Unity-Technologies/NotificationsSamples#36]
Without **"help1.Style = NotificationStyle.BigTextStyle;"** I can see both small & large icons, but with it, I see default unity small icon only next to the title.

Unity 2020.1.0a18
Package 1.0.4 Preview.5

```
private void SendHelp1()
    {
        var help1 = new AndroidNotification();
        help1.Title = "Tanks World: Arena";
        help1.Text = "Did you know you can read ability and stats descriptions, when you tap on them in menu?";
        help1.SmallIcon = "small";
        help1.LargeIcon = "large";
        help1.Style = NotificationStyle.BigTextStyle;
        help1.FireTime = System.DateTime.Now.AddMinutes(1);
        help1.ShouldAutoCancel = true;

        if (AndroidNotificationCenter.CheckScheduledNotificationStatus(h1) == NotificationStatus.Delivered)
        {
            h1 = AndroidNotificationCenter.SendNotification(help1, channelId);
        }
        
    }
```

**Comment by Nyankoo** [comment]
@aurimasc Are Styles still supported? Can't seem to set them with the latest version.

**Comment by vaidasma** [comment]
We're not able to reproduce this issue on Notification package 1.4.1 . 

If you're still experiencing this issue on the mentioned release, please submit another issue with included info about your device, it's OS, used Unity release, and any other information that you might have that's potentially relevant.
