### ISSUE TITLE
Error when building with the Notification Package

### ISSUE THREAD

**Issue by rafael-f** [Unity-Technologies/NotificationsSamples#37]
I guess this needs to be updated, I'm now getting this error when trying to build with the Notification Package:

  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class android.support.v4.app.INotificationSideChannel found in modules classes.jar (:androidx.core.core-1.1.0:) and classes.jar (com.android.support:support-compat:27.1.1)

**Comment by ghost** [comment]
Was fighting with this all day. IOS works fantastic, but Android is broken. Was getting the same error as you in Unity 2019.3.7f. Honestly I hate doing Android builds with any extra SDKs.... anyways...
Noticed in the package manager they are using package version 1.0.4 preview 2. Did a build and seemed to have worked.

**Comment by unadamlar** [comment]
Same issue here in Unity 2019.3.0f3. Package version preview1.1.0 and preview1.2.0 will fail the build with this error. Reverting to preview9-1.0.4 works fine. Also using FacebookSDK, Google Play Games, and Firebase plugins

**Comment by aurimasc** [comment]
Looks like an out of date issue.
