### ISSUE TITLE
Getting native notifications that were received when the app wasn't running

### ISSUE THREAD

**Issue by Fellhuhn** [Unity-Technologies/NotificationsSamples#40]
When the app is not running remote notifications are displayed as native notifications. When the app gets into the foreground again the registered listeners/handlers aren't triggered at the moment.

Is there any way to access the native notifications (on Android and iOS) so that they can be handled as usual?

This currently only happens when the user clicks the notifications but that can't be expected from him (especially as there can be >10 notifications).

**Comment by aurimasc** [comment]
You can only get notifications on iOS using iOSNotificationCenter.GetScheduledNotifications and iOSNotificationCenter.GetDeliveredNotifications
