### ISSUE TITLE
Reschedule Notifications on Device Restart does'nt works

### ISSUE THREAD

**Issue by BenDevelopment** [Unity-Technologies/NotificationsSamples#43]
Hi,

Reschedule Notifications on Device Restart doesn't works. Tested on OnePlus 6T, Android 9.
Once the smartphone has restarted, all the notifications are ignored. I have to run the application to reactivate the notificaitons (all the missing notifications appears at the same time when I start the application).

**Comment by aurimasc** [comment]
It does work in latest release when we tried. Unless there is something specific to mentioned device or even it's settings.
