### ISSUE TITLE
Remote notifications doubt

### ISSUE THREAD

**Issue by EricBatlle** [Unity-Technologies/NotificationsSamples#45]
More than an issue is a doubt: 

How can I make push notifications remotely?

I think that the concept of "scheduling" notifications won't work if I want to send any notification from my Server, isn't it? Should I merge this system with firebase? just pick one? 

Thanks for the information

**Comment by aurimasc** [comment]
In case of iOS you can use Apple push notification service.
In case of Android you need a solution that has server side for it.
In any case, this is out of scope for this repo.
