### ISSUE TITLE
Firebase OnChildAdded Listener instead of NewsFeedReader ?

### ISSUE THREAD

**Issue by FLYINGSKATE** [Unity-Technologies/NotificationsSamples#46]
Where you are fetching docs from NewsFeed Unity .....Can I use Firebase OnChildAdded Listener there and get a notification ???? Even when the app is not running????Please tell me I can...

**Comment by aurimasc** [comment]
Based on the following issue, there are compatibility problems between Firebase and Unity notifications package. See my last comment in it for more details.
https://github.com/Unity-Technologies/NotificationsSamples/issues/35
