### ISSUE TITLE
IL2CPP error: SafeArray element type Int64 is not supported

### ISSUE THREAD

**Issue by milamila33** [Unity-Technologies/NotificationsSamples#48]
i am getting this error on unity 2019.2.4f1. Should i change the unity version?

**Comment by vaidas-unity** [comment]
Hi @milamila33, we no longer support 2019.2, would you mind switching to 2019.4 long term support release and checking if the issue persists?

**Comment by vaidas-unity** [comment]
Looks like the upgrade should fix it, closing.
