### ISSUE TITLE
Authorization for Android just like we have for iOS

### ISSUE THREAD

**Issue by kenofori** [Unity-Technologies/NotificationsSamples#53]
Hi there,

What if user reject the notification permission for android and then we'd like 2 things

1- a property that returns whether android permission is granted or rejected
2- if its reject then show a authorization dialog just like we have on iOS

Thanks

**Comment by vaidasma** [comment]
Hey, permissions have been expanded to have additional functionality, that includes having callbacks for different permission states, which I believe is what you're looking for. Permission callbacks are available from 2020.x Unity releases:

https://docs.unity3d.com/ScriptReference/Android.Permission.RequestUserPermission.html

If you have more questions or concerns, feel free to contact us any time!
