### ISSUE TITLE
Clear Badge Number

### ISSUE THREAD

**Issue by rpassareti** [Unity-Technologies/NotificationsSamples#57]
I'm trying to clear the notifications and the badge number when you open the app, but something is missing for me

I read in one post, to call "AndroidNotification.ShouldAutoCancel", but it only works if you click in the notification, if you click the app icon, nothing changes
and if it's 3 notification, only one is dismiss, the other 2 keeps there.

any tips or idea?

**Comment by aurimasc** [comment]
You have to cancel notifications I believe.
