### ISSUE TITLE
Will there be more customizations added for Android? (Changing background image, sound and e.t.c)

### ISSUE THREAD

**Issue by NarekSaghiyan** [Unity-Technologies/NotificationsSamples#61]
A lot of games on Android have great notifications with custom background image, sound. I would like to add that to my notifications as well, but as far as I am concerned there is no option for that, I saw that custom sounds was planned to be done for Mobile Notifications Plugin (there was a TO DO comment in source code), but 2 years later it was never added.

**Comment by vaidasma** [comment]
Request submitted to the developer. No ETA yet, but it's most likely on the way!

**Comment by sumaliqinghua** [comment]
Is this function implemented? I also need this
