### ISSUE TITLE
Problem of AndroidNotificationCenter in overload of NotificationReceivedCallback delegate

### ISSUE THREAD

**Issue by KooroshRH** [Unity-Technologies/NotificationsSamples#63]
I think there is a bug in the `OnLocalNotificationReceived` arguments while we want to add this method to the `NotificationReceivedCallback` delegate.
I have changed this argument to single `AndroidNotificationIntentData` and the problem has solved.

**Comment by aurimasc** [comment]
That is the argument for it in latest notifications package code.
