### ISSUE TITLE
Demo build error 

### ISSUE THREAD

**Issue by Sami-AlEsh** [Unity-Technologies/NotificationsSamples#66]
Version: Unity 2020.1.17f1
Platform: Android

Steps:
1- Clone this repo
2- open project in unity 2020.1.17f1
3- switch platform to Android
4- Build :)

Build Error:
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :launcher
WARNING: The option 'android.enableR8' is deprecated and should not be used anymore.
It will be removed in a future version of the Android Gradle plugin, and will no longer allow you to disable R8.

> Task :unityLibrary:preBuild UP-TO-DATE
> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseBuildConfig
> Task :launcher:generateReleaseBuildConfig
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseResValues
> Task :unityLibrary:generateReleaseResources
> Task :launcher:mainApkListPersistenceRelease
> Task :launcher:generateReleaseResValues
> Task :launcher:generateReleaseResources
> Task :launcher:createReleaseCompatibleScreenManifests
> Task :launcher:extractDeepLinksRelease
> Task :launcher:prepareLintJar
> Task :unityLibrary:packageReleaseResources
> Task :launcher:checkReleaseDuplicateClasses
> Task :unityLibrary:javaPreCompileRelease
> Task :unityLibrary:extractDeepLinksRelease
> Task :unityLibrary:compileReleaseLibraryResources
> Task :unityLibrary:prepareLintJarForPublish
> Task :unityLibrary:processReleaseManifest
> Task :launcher:processReleaseManifest
> Task :launcher:mergeReleaseShaders
> Task :unityLibrary:parseReleaseLocalResources
> Task :launcher:compileReleaseShaders
> Task :launcher:generateReleaseAssets
> Task :launcher:processReleaseJavaRes NO-SOURCE
> Task :launcher:mergeReleaseJniLibFolders
> Task :launcher:validateSigningRelease
> Task :unityLibrary:mergeReleaseShaders
> Task :unityLibrary:compileReleaseShaders
> Task :unityLibrary:generateReleaseAssets
> Task :launcher:mergeReleaseResources
> Task :launcher:desugarReleaseFileDependencies
> Task :launcher:mergeExtDexRelease
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :launcher:mergeReleaseAssets
> Task :unityLibrary:mergeReleaseJniLibFolders
> Task :unityLibrary:generateReleaseRFile
> Task :launcher:processReleaseResources

> Task :unityLibrary:compileReleaseJavaWithJavac

> Task :unityLibrary:mergeReleaseNativeLibs
> Task :unityLibrary:bundleLibResRelease
> Task :launcher:mergeReleaseJavaResource
> Task :unityLibrary:stripReleaseDebugSymbols
> Task :unityLibrary:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:bundleLibCompileRelease
> Task :unityLibrary:bundleLibRuntimeRelease
> Task :launcher:javaPreCompileRelease
> Task :launcher:compileReleaseJavaWithJavac
> Task :launcher:compileReleaseSources
> Task :launcher:lintVitalRelease FAILED
> Task :launcher:mergeReleaseNativeLibs
43 actionable tasks: 43 executed

UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by aurimasc** [comment]
This look like a problem with tools on your machine, not something related to notifications package.
If besides Unity you run some other Android tools (like Android Studio), you may have compatibility issues with stuff like adb or gradle daemons.
Actually, is this even an error, not a warning?

**Comment by Sami-AlEsh** [comment]
Yup, this is an error because build process was stopped and failed.
Do you know how to fix it ?
I've been working with Unity for a while and I didn't face such a problem!

**Comment by aurimasc** [comment]
Check the running processes on your machine. Maybe you use some other Android software that also uses gradle, like Android Studio, then you may have incompatible gradle versions present.
