### ISSUE TITLE
AndroidNotificationCenter.GetLastNotificationIntent() Not being refreshed

### ISSUE THREAD

**Issue by Zynek90** [Unity-Technologies/NotificationsSamples#7]
Hello i have following problem... repro stepts:
0) Install app
1) I SendNotificationWithExplicitID with IntentData
2) Close app
3) Wait for the notification and open app with it
4) Get IntentData of AndroidNotificationCenter.GetLastNotificationIntent()
- Works all right so far
5) repeat steps 1-4 with different notification and IntentData
- This time i get IntentData from the first notification even though device displayed the new notification.
So every time i open app with notification i get IntentData from the first notification.
I tried Canceling the first notification after i get IntentData, but it doesn't help.
Happens on Nvidia Shield Android 7.0

Is there something I am missing ?

**Comment by YehudaK** [comment]
Hi, I cannot reproduce your error. I was getting every time new intent with both SendNotification() and SendNotificationWithExplicitID(). I want also ask you, if you really CLOSE app or just minimize? When I start closed app with notification, GetLastNotificationIntent() always returns null? Thanks

**Comment by Zynek90** [comment]
> Hi, I cannot reproduce your error. I was getting every time new intent with both SendNotification() and SendNotificationWithExplicitID(). I want also ask you, if you really CLOSE app or just minimize? When I start closed app with notification, GetLastNotificationIntent() always returns null? Thanks

Hi, yes i force quit the app. Maybe it's the way i am using SendNotificationWithExplicitID. I have constant id for each notification. Any idea what happens if i SendNotificationWithExplicitID with Id of already registered notification ? I couldn't find it in the documentation and i assumed it overrides old notification which would be nice.

**Comment by YehudaK** [comment]
At first, by mistake, I scheduled all notifications with the same ID an they were not called... the first one should be called within 10 second but taking in an account what you said, I understand why it happened. The new notifications with same ID will simply overwrite the previous one, just like UpdateScheduledNotifcation().

Could you post the code fragment which you use to get GetLastNotificationIntent and also from where exactly you are calling it? Some android functions can be executed only in the main thread, so I want to see how my code is different from yours, why you are getting last notification intent while I am getting null if app was hard closed. Thanks

Thanks

**Comment by Zynek90** [comment]
Yes it runs on the main thread.

The code is very simple
```
public string RetrieveLastNotificationIntentData()
        {
            var notificationIntentData = AndroidNotificationCenter.GetLastNotificationIntent();
            if (notificationIntentData != null)
            {
                var notification = notificationIntentData.Notification;

                AndroidNotificationCenter.CancelDisplayedNotification(notificationIntentData.Id);
                return notification.IntentData;                
            }
            return "";
        }
```
I guess it's something else. I will perform more tests.

**Comment by YehudaK** [comment]
> Yes it runs on the main thread.
> The code is very simple

That's strange, I am doing the same but after hard close I am not able to get notification which started the app. Probably I need to test with other mobiles and different android versions. I also bought **[Simple Android Notifications](https://assetstore.unity.com/packages/tools/integration/simple-android-notifications-71294)** plugin to give a try and check if it's will give better result.

**Comment by vaidasma** [comment]
We're not able to reproduce this issue on Notification package 1.4.1 .

If you're still experiencing this issue on the mentioned release, please submit another issue with included info about your device, it's OS, used Unity release, and any other information that you might have that's potentially relevant.

It would be great if you'd do this via Unity bug reported within the editor and attach the reproduction project so we would be able to investigate it!
