### ISSUE TITLE
Android - Code Error on PermissionRequest() and PermissionStatus

### ISSUE THREAD

**Issue by muradmohdzain** [Unity-Technologies/NotificationsSamples#74]
![image](https://user-images.githubusercontent.com/4339714/200135840-ee23acd3-fe5d-46b0-8202-f8741432159a.png)

**Comment by aprius** [comment]
You need upgrade version unity notification to newest version 2.1.0

**Comment by muradmohdzain** [comment]
Thanks for the quick reply. But I can't find a way how to upgrade from current version.

![image](https://user-images.githubusercontent.com/4339714/200137713-1ef18951-899f-4f9b-af8c-3ed07842e0de.png)

**Comment by yenmoc** [comment]
You can upgrade it directy in file manifest.jsonSent from my iPhoneOn Nov 6, 2022, at 2:31 AM, muradmohdzain ***@***.***> wrote:﻿
Thanks for the quick reply. But I can't find a way how to upgrade from current version.

**Comment by aprius** [comment]
<img width="466" alt="Screen Shot 2022-11-06 at 4 14 10 PM" src="https://user-images.githubusercontent.com/44673303/200163049-32018753-3dab-45de-9463-645e77fec1a4.png">

You can change version directly in file manifest.json
