### ISSUE TITLE
Android Repeatad Notifcations

### ISSUE THREAD

**Issue by uzayayan** [Unity-Technologies/NotificationsSamples#78]
Hello guys!

I am working on a code that sends notifications to users every evening at 7 o'clock, but I am facing some issues on the Android side. If I set the RepeatInterval value to "TimeSpan.Zero," the notification is sent at exactly 7 o'clock in the evening. However, when I set it to "new TimeSpan(1, 0, 0, 0)" for it to repeat every day, the notification starts coming at 1 o'clock in the afternoon instead of 7 o'clock in the evening. I've tried various approaches, and I can't figure out if this is a bug or if I'm overlooking something. By the way, I'm testing the notifications by changing the local time of my device.

I am awaiting your assistance.

Unity Version : 2022.3.16f1
Mobile Notifications Version : 2.3.1

```
public AndroidNotification GetAndroidNotification()
{
    var nowTime = DateTime.Now;
    var fireTime = new DateTime(nowTime.Year, nowTime.Month, nowTime.Day, Hour, Minute, Second);

    if (nowTime >= fireTime)
    {
        fireTime = fireTime.AddDays(1);
    }

    return new AndroidNotification()
    {
        FireTime = fireTime,
        Title = Title,
        Text = Text,
        SmallIcon = SmallIcon,
        LargeIcon = LargeIcon,
        ShouldAutoCancel = true,
        RepeatInterval = IsRepeat ? new TimeSpan(RepeatDay, RepeatHour, RepeatMinute, RepeatSecond) : TimeSpan.Zero
    };
}
```

```
var androidNotification = notificationBlueprint.GetAndroidNotification();
var notificationStatus = AndroidNotificationCenter.CheckScheduledNotificationStatus(notificationBlueprint.Id);

switch (notificationStatus)
{
    case NotificationStatus.Unknown:
        
        AndroidNotificationCenter.SendNotificationWithExplicitID(androidNotification, notificationBlueprint.Channel, notificationBlueprint.Id);

        break;
    case NotificationStatus.Scheduled:
        
        AndroidNotificationCenter.UpdateScheduledNotification(notificationBlueprint.Id, androidNotification, notificationBlueprint.Channel);
        
        break;
    case NotificationStatus.Delivered:
        
        AndroidNotificationCenter.CancelNotification(notificationBlueprint.Id);
        
        break;
}

```

**Comment by aurimasc** [comment]
Notifications are scheduled using UTC, that may mess things up.
Please, don't use this for bug reports other than issues with a sample itself. It isn't frequently monitored as you can see.
